version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./db/data:/data/db
    env_file:
      - .env

  api:
    build:
      context: ./tacs-articles-api
    ports:
      - "8080:8080"
    environment:
      CON_STRING: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/
      MONGO_DB: ${MONGO_DB}
    env_file:
      - .env

  bot:
    build:
      context: ./tacs-telegram-bot
    environment:
      RESOURCE_URL: ${RESOURCE_URL}
      BOT_TOKEN: ${BOT_TOKEN}
      BOT_USERNAME: ${BOT_USERNAME}
    env_file:
      - .env
