version: '4.1'

services:

  redis:
    image: redis:7.2.5
    container_name: redis
    ports:
      - "6379:6379"

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./db/data:/data/db
    env_file:
      - .env

  api:
    build:
      context: ./tacs-articles-api
    ports:
      - "8080:8080"
    environment:
      CON_STRING: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/
      MONGO_DB: ${MONGO_DB}
    env_file:
      - .env

  bot:
    build:
      context: ./tacs-telegram-bot
    environment:
      RESOURCE_URL: http://api:8080/app
      BOT_TOKEN: ${BOT_TOKEN}
      BOT_USERNAME: ${BOT_USERNAME}
      NOTIFICATION_REFRESHING_TIME: ${NOTIFICATION_REFRESHING_TIME}
      REDIS_CON_STRING: ${REDIS_CON_STRING}
    env_file:
      - .env

  web:
    build:
      context: ./tacs-front
    ports:
      - "80:80"
    stdin_open: true
    tty: true
