version: '4.0'

services:
  redis:
    image: redis:7.2.5
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - bot-database

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./db/data:/data/db
    env_file:
      - .env
    networks:
      - backend-database

  api:
    build:
      context: ./tacs-articles-api
    ports:
      - "8080:8080"
    environment:
      CON_STRING: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/
      MONGO_DB: ${MONGO_DB}
    env_file:
      - .env
    networks:
      - backend
      - bot
      - backend-database

  bot:
    build:
      context: ./tacs-telegram-bot
    environment:
      RESOURCE_URL: ${RESOURCE_URL}
      BOT_TOKEN: ${BOT_TOKEN}
      BOT_USERNAME: ${BOT_USERNAME}
      NOTIFICATION_REFRESHING_TIME: ${NOTIFICATION_REFRESHING_TIME}
      REDIS_CON_STRING: ${REDIS_CON_STRING}
    env_file:
      - .env
    networks:
      - bot
      - bot-database
      - backend
networks:
  bot:
  bot-database:
  backend:
  backend-database:
